traigo lo anterior
MATarg81/proyecto-final pull request #128
Opened 2022-10-29 16:45 UTC by Cinthyavmf

2022-10-29 17:01 UTC, MATarg81 reviewed
Ya lo subo yo corregido

2022-10-29 17:07 UTC, wellnahuel approved these changes

2022-10-30 16:37 UTC, Azrux approved these changes

2022-10-30 16:47 UTC, MATarg81 requested changes
Borralo nomas a este pr Cin, ya está

2022-10-31 15:39 UTC, closed without merging